require:
 - rubocop-rails
 - rubocop-rspec

Rails:
  Enabled: true

AllCops:
 TargetRubyVersion: 3.0.2
 DisplayCopNames: true
 NewCops: enable
 Exclude: 
    - bin/**/*
    - config/initializers/secure_headers.rb
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
Discourse/NoChdir:
  Enabled: false   

inherit_gem :
   rubocop-discourse : default.yml 
   
Rails/FilePath:
  EnforcedStyle: arguments

RSpec/Capybara/FeatureMethods:
 EnabledMethods:
    - background
    - feature
    - scenario

RSpec/MultipleMemoizedHelpers:
 Enabled: false

RSpec/MultipleExpectations:
 Enabled: false
 
RSpec/PredicateMatcher:
 Enabled: false 

Layout/LineLength:
 Max: 140

Style/FrozenStringLiteralComment:
 Enabled: false

Style/Documentation:
 Enabled: false

Metrics/MethodLength:
 Max: 12

Metrics/BlockLength:
 Enabled: false

Style/ClassAndModuleChildren:
 Enabled: false

Metrics/CyclomaticComplexity:
 Max: 9

Metrics/PerceivedComplexity:
 Max: 9

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded
    
RSpec/ExampleLength:
  Enabled: false